/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 2074f976774a25ce5c62d20d47b5e6ed)
interface __BaseEnv_Env {
  OAUTH_KV: KVNamespace
  HYPERDRIVE: Hyperdrive
  ASSETS: Fetcher
  MCP_RESOURCE: 'https://mailhub.bktsk.com/mcp'
  ACCESS_CLIENT_ID: string
  ACCESS_CLIENT_SECRET: string
  ACCESS_TOKEN_URL: string
  ACCESS_AUTHORIZATION_URL: string
  ACCESS_JWKS_URL: string
  ALLOWED_EMAILS: string
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/server')
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'MCP_RESOURCE'
      | 'ACCESS_CLIENT_ID'
      | 'ACCESS_CLIENT_SECRET'
      | 'ACCESS_TOKEN_URL'
      | 'ACCESS_AUTHORIZATION_URL'
      | 'ACCESS_JWKS_URL'
      | 'ALLOWED_EMAILS'
    >
  > {}
}
